CREATE OR REPLACE PACKAGE LVL1 AS 

  PROCEDURE ADD_USER(
    ONAME IN VARCHAR2,
    ORANK IN VARCHAR2,
    OPWD IN VARCHAR2,
    SNAME IN VARCHAR2
  ); 
  
  PROCEDURE DELETE_USER(
    OFID IN NUMBER
  );
    
  PROCEDURE EDIT_USER(
    OFID IN NUMBER,
    ONAME IN VARCHAR2,
    ORANK IN VARCHAR2,
    SNAME IN VARCHAR2
  );
  
  FUNCTION FIND_STATION(
    SNAME IN VARCHAR2
  )RETURN NUMBER;
  
  PROCEDURE ADD_STATION(
    STNAME IN VARCHAR2,
    STADDR IN VARCHAR2,
    STZONE IN VARCHAR2
  ); 
  
  PROCEDURE DELETE_STATION(
    STID IN NUMBER
  );
    
  PROCEDURE EDIT_STATION(
    STID IN NUMBER,
    STNAME IN VARCHAR2,
    STADDR IN VARCHAR2,
    STZONE IN VARCHAR2
  );
END LVL1; 

CREATE OR REPLACE PACKAGE BODY LVL1 AS 

  PROCEDURE ADD_USER(
    ONAME IN VARCHAR2,
    ORANK IN VARCHAR2,
    OPWD IN VARCHAR2,
    SNAME IN VARCHAR2
  ) IS
  OFID NUMBER;
  OLVL NUMBER;
  BEGIN
    OFID:= TJPD.OFFICER_SEQ.NEXTVAL;
    CASE WHEN ORANK = 'Cadete' THEN
        OLVL:= 1;
    WHEN ORANK = 'Oficial de Policia' THEN
        OLVL:= 2;
    WHEN ORANK = 'Detective' OR ORANK = 'Inspector' THEN
        OLVL:= 3;
    WHEN ORANK = 'Comandante' OR ORANK = 'Teniente' THEN
        OLVL:= 4;
    WHEN ORANK = 'Comisionado' THEN
        OLVL:= 5;
    WHEN ORANK = 'Jefe de Policia' THEN
        OLVL:= 6;
    END CASE;
    INSERT INTO TJPD.OFFICER
    VALUES (OFID, ONAME, ORANK, OPWD, OLVL);

    INSERT INTO TJPD.OFFICER_STATION
    VALUES (TJPD.OFFICER_STATION_SEQ.NEXTVAL, OFID, FIND_STATION(SNAME));
    COMMIT; 
  END ADD_USER; 


  PROCEDURE DELETE_USER(
    OFID IN NUMBER
  ) IS
  BEGIN
    DELETE FROM TJPD.OFFICER_STATION
        WHERE TJPD.OFFICER_STATION.OFFICER_ID = OFID;
    DELETE FROM TJPD.OFFICER	
        WHERE TJPD.OFFICER.OFFICER_ID = OFID;
    COMMIT;
  END DELETE_USER;
  
  
  PROCEDURE EDIT_USER(
    OFID IN NUMBER,
    ONAME IN VARCHAR2,
    ORANK IN VARCHAR2,
    SNAME IN VARCHAR2
  ) IS
  OLVL NUMBER;
  BEGIN
    CASE WHEN ORANK = 'Cadete' THEN
        OLVL:= 1;
    WHEN ORANK = 'Oficial de Policia' THEN
        OLVL:= 2;
    WHEN ORANK = 'Detective' OR ORANK = 'Inspector' THEN
        OLVL:= 3;
    WHEN ORANK = 'Comandante' OR ORANK = 'Teniente' THEN
        OLVL:= 4;
    WHEN ORANK = 'Comisionado' THEN
        OLVL:= 5;
    WHEN ORANK = 'Jefe de Policia' THEN
        OLVL:= 6;
    END CASE;
    UPDATE TJPD.OFFICER
        SET TJPD.OFFICER.OFFICER_NAME = ONAME, 
            TJPD.OFFICER.OFFICER_RANK = ORANK, 
            TJPD.OFFICER.USER_LEVEL = OLVL
        WHERE TJPD.OFFICER.OFFICER_ID = OFID;
        
    UPDATE TJPD.OFFICER_STATION
        SET TJPD.OFFICER_STATION.STATION_ID = FIND_STATION(SNAME)
        WHERE TJPD.OFFICER_STATION.OFFICER_ID = OFID;
    COMMIT;
  END EDIT_USER;
  
  FUNCTION FIND_STATION(
    SNAME IN VARCHAR2
  )RETURN NUMBER
  IS
  STID NUMBER;
  BEGIN
    SELECT TJPD.STATION.STATION_ID	INTO STID
    FROM TJPD.STATION 
    WHERE TJPD.STATION.STATION_NAME = SNAME;
    RETURN STID;
  END;
  
  
  PROCEDURE ADD_STATION(
    STNAME IN VARCHAR2,
    STADDR IN VARCHAR2,
    STZONE IN VARCHAR2
  ) IS
  BEGIN
    INSERT INTO TJPD.STATION
    VALUES (TJPD.STATION_SEQ.NEXTVAL, STNAME, STADDR, STZONE);
    COMMIT; 
  END ADD_STATION; 


  PROCEDURE DELETE_STATION(
    STID IN NUMBER
  ) IS
  BEGIN
    DELETE FROM TJPD.OFFICER_STATION
        WHERE TJPD.OFFICER_STATION.STATION_ID = STID;
    DELETE FROM TJPD.STATION	
        WHERE TJPD.STATION.STATION_ID = STID;
    COMMIT;
  END DELETE_STATION;
  
  
  PROCEDURE EDIT_STATION(
    STID IN NUMBER,
    STNAME IN VARCHAR2,
    STADDR IN VARCHAR2,
    STZONE IN VARCHAR2
  ) IS
  BEGIN
    UPDATE TJPD.STATION
        SET TJPD.STATION.STATION_NAME = STNAME, 
            TJPD.STATION.STATION_ADDRESS = STADDR, 
            TJPD.STATION.STATION_ZONE = STZONE
        WHERE TJPD.STATION.STATION_ID = STID;
    COMMIT;
  END EDIT_STATION;
END LVL1; 

SHOW ERRORS