CREATE OR REPLACE PACKAGE LVL2 AS 

  PROCEDURE ADD_FIR(
    OFID IN NUMBER,
    STID IN NUMBER,
    IDATE IN DATE,
    ITIME IN TIMESTAMP,
    IPLACE IN VARCHAR2,
    VNAME IN VARCHAR2,
    VADR IN VARCHAR2,
    VGENDER IN VARCHAR2,
    VAGE IN NUMBER,
    ANAME IN VARCHAR2,
    AADR IN VARCHAR2,
    AGENDER IN VARCHAR2,
    AAGE IN NUMBER,
    PNAME IN VARCHAR2,
    PADR IN VARCHAR2
  ); 
  
  PROCEDURE UPDATE_FIR(
    FIRID IN NUMBER,
    OFID IN NUMBER,
    STID IN NUMBER,
    IDATE IN DATE,
    ITIME IN TIMESTAMP,
    IPLACE IN VARCHAR2,
    VNAME IN VARCHAR2,
    VADR IN VARCHAR2,
    VGENDER IN VARCHAR2,
    VAGE IN NUMBER,
    ANAME IN VARCHAR2,
    AADR IN VARCHAR2,
    AGENDER IN VARCHAR2,
    AAGE IN NUMBER,
    PNAME IN VARCHAR2,
    PADR IN VARCHAR2
  );
END LVL2; 

CREATE OR REPLACE PACKAGE BODY LVL2 AS 

  PROCEDURE ADD_FIR(
    OFID IN NUMBER,
    STID IN NUMBER,
    IDATE IN DATE,
    ITIME IN TIMESTAMP,
    IPLACE IN VARCHAR2,
    VNAME IN VARCHAR2,
    VADR IN VARCHAR2,
    VGENDER IN VARCHAR2,
    VAGE IN NUMBER,
    ANAME IN VARCHAR2,
    AADR IN VARCHAR2,
    AGENDER IN VARCHAR2,
    AAGE IN NUMBER,
    PNAME IN VARCHAR2,
    PADR IN VARCHAR2
  ) IS
    FIRID NUMBER;
  BEGIN
    FIRID:= TJPD.FIR_SEQ.NEXTVAL;
    INSERT INTO TJPD.FIR
    VALUES (FIRID, OFID, STID, IDATE, ITIME, IPLACE);
    INSERT INTO TJPD.VICTIM (VICTIM_ID,FIR_ID,VIC_NAME,ADDRESS,AGE,GENDER)
    VALUES (TJPD.VICTIM_SEQ.NEXTVAL, FIRID, VNAME, VADR, VGENDER, VAGE);
    INSERT INTO TJPD.ACCUSED (ACCUSED_ID,FIR_ID,ACCUSED_NAME,ADDRESS,AGE,GENDER)
    VALUES (TJPD.ACCUSED_SEQ.NEXTVAL, FIRID, ANAME, AADR, AGENDER, AAGE);
    INSERT INTO TJPD.PETITIONER
    VALUES (TJPD.PETITIONER_SEQ.NEXTVAL, FIRID, PNAME, PADR);
    COMMIT; 
  END ADD_FIR; 


  PROCEDURE UPDATE_FIR(
    FIRID IN NUMBER,
    OFID IN NUMBER,
    STID IN NUMBER,
    IDATE IN DATE,
    ITIME IN TIMESTAMP,
    IPLACE IN VARCHAR2,
    VNAME IN VARCHAR2,
    VADR IN VARCHAR2,
    VGENDER IN VARCHAR2,
    VAGE IN NUMBER,
    ANAME IN VARCHAR2,
    AADR IN VARCHAR2,
    AGENDER IN VARCHAR2,
    AAGE IN NUMBER,
    PNAME IN VARCHAR2,
    PADR IN VARCHAR2
  ) IS
  BEGIN
    UPDATE TJPD.FIR
        SET TJPD.FIR.OFFICER_ID = OFID, 
            TJPD.FIR.STATION_ID = STID, 
            TJPD.FIR.INCIDENT_DATE = IDATE,
            TJPD.FIR.INCIDENT_TIME = ITIME,
            TJPD.FIR.INCIDENT_PLACE = IPLACE
        WHERE TJPD.FIR.FIR_ID = FIRID;
    UPDATE TJPD.VICTIM
        SET TJPD.VICTIM.VIC_NAME = VNAME, 
            TJPD.VICTIM.ADDRESS = VADR, 
            TJPD.VICTIM.GENDER = VGENDER,
            TJPD.VICTIM.AGE = VAGE
        WHERE TJPD.VICTIM.FIR_ID = FIRID;
    UPDATE TJPD.ACCUSED
        SET TJPD.ACCUSED.ACCUSED_NAME = ANAME, 
            TJPD.ACCUSED.ADDRESS = AADR, 
            TJPD.ACCUSED.GENDER = AGENDER,
            TJPD.ACCUSED.AGE = AAGE
        WHERE TJPD.ACCUSED.FIR_ID = FIRID;
    UPDATE TJPD.PETITIONER
        SET TJPD.PETITIONER.PET_NAME = PNAME, 
            TJPD.PETITIONER.ADDRESS = PADR
        WHERE TJPD.PETITIONER.FIR_ID = FIRID;
    COMMIT;
  END UPDATE_FIR;
END LVL2; 

SHOW ERRORS